로그인 기능 추가
tripmate-manager/TripMATE pull request #14
Opened 2023-01-20 04:15 UTC by cjyeon

2023-01-20 04:29 UTC, yuncorn commented on src/main/java/com/tripmate/controller/MemberController.java
> +                MemberDTO signInResult = response.getData().get(0);
npe 방지 로직 추가해주세요.

2023-01-20 04:37 UTC, yuncorn commented on src/main/webapp/WEB-INF/jsp/member/signIn.jsp
> +<div class="signin__wrap">
각 class 명 사이에 언더바 개수가 다른데 특별한 의도가 있는건가요?

2023-01-20 04:52 UTC, cyjang-pionnet commented on src/main/java/com/tripmate/controller/MemberController.java
> +        ModelAndView mav = new ModelAndView();
로그인 실패 시 로그인 시도 횟수를 추가시키는 부분이 보이지 않아요!
5번 실패 시 인증 후 로그인 부분과 함께 추가 요청 드리겠습니다

2023-01-20 05:14 UTC, Ryumina commented on src/main/webapp/resources/js/member/signIn.js
> +        window.location.href = "/forward/members/signUp.trip";
url 잘못된 것 같습니다.
회원가입 페이지로 이동시켜야 하는데
회원가입 처리를 하는 메서드를 태우고 있네요

2023-01-20 05:20 UTC, Ryumina commented on src/main/webapp/resources/js/member/signIn.js
> +        window.location.href = "/forward/members/signUp.trip";
아이디 찾기, 비밀번호 찾기도 아직 화면은 구현이 안되어 있는 것 같지만
url 확인 부탁드립니다!

2023-01-20 05:23 UTC, yuncorn commented on src/main/webapp/resources/js/member/signIn.js
> +        window.location.href = "/forward/members/signUp.trip";
컨트롤러단에서 반복적으로 단순 jsp페이지를 호출하던 메서드를 제거하기 위해  ForwardController를 만들어서 경로 앞에 /forward를 붙여주면 WEB-INF/jsp 경로의 jsp페이지로 이동하도록 구현되어 있습니다.
그래서 회원가입 페이지로 이동하는건 맞는데 패키지 경로가 members가 아니라 member로 해야 정상 작동 할겁니다.

2023-01-20 05:30 UTC, Ryumina commented on src/main/webapp/WEB-INF/jsp/member/signIn.jsp
> +    <script src="<%=Const.STATIC_JS_PATH%>/member/validationCheck.js"></script>
추후에 validationCheck.js 에서 유효성 체크를 진행할 때
빈 값 체크에서 추가로 공백 체크도 추가해주시면 좋을 것 같습니다.

로그인 페이지에서 인위적으로 공백을 넣고 로그인을 시도했을 때
정상적으로 가입 여부를 체크하고 있는데 이를 방지하기 위해
공백 체크를 하는 로직도 추가되었으면 합니다!

2023-01-25 00:56 UTC, Lets-KT commented
ID 중복 체크했음에도 불구하고 가입시도 시, ID 중복체크가 뜨고 있네요.
스크립트 로직 확인이 필요해 보입니다.

2023-01-25 01:36 UTC, cyjang-pionnet commented on src/main/webapp/resources/js/members/signIn.js
> +                        return false;
횟수 초과할 경우 후처리는 없나요? 페이지 이동이라던지요!

2023-01-25 01:46 UTC, Lets-KT commented
회원가입 -> 메일 회신 후 메일 내의 "이메일 인증하기" 클릭 -> 로그인페이지 이동 후 로그인 시도 -> 인증메일 발송 페이지(http://localhost:8080/forward/members/signUpResult.trip) 로 이동.

회원가입 플로우가 이상해보이는데요. 인증쪽 작업 진행중이라 그런건가요?

2023-01-25 01:48 UTC, cjyeon commented
> ID 중복 체크했음에도 불구하고 가입시도 시, ID 중복체크가 뜨고 있네요. 스크립트 로직 확인이 필요해 보입니다.

수정완료했습니다.

2023-01-25 01:50 UTC, cjyeon commented
> 회원가입 -> 메일 회신 후 메일 내의 "이메일 인증하기" 클릭 -> 로그인페이지 이동 후 로그인 시도 -> 인증메일 발송 페이지(http://localhost:8080/forward/members/signUpResult.trip) 로 이동.
> 
> 회원가입 플로우가 이상해보이는데요. 인증쪽 작업 진행중이라 그런건가요?

넵 일단 주석에 적어두긴 했는데, main 화면 추가 시 main으로 이동하도록 수정할 예정입니다.

2023-01-25 01:56 UTC, wjdwo951219 commented on src/main/java/com/tripmate/controller/MemberController.java
> +        } catch (Exception e) {
catch block 2개 내용이 같습니다. 불필요한 분기 처리라면 Exception catch block 하나로 통합해도 좋을 것 같아요.

2023-01-25 01:56 UTC, wjdwo951219 commented on src/main/java/com/tripmate/domain/SignInDTO.java
> +@Setter
이 프로젝트에서는 setter 사용하지 않는 것 같습니다. 제거 요청 드립니다. 만약 사용하는 부분 있으면 그냥 패스해주세요.

2023-01-25 04:18 UTC, yuncorn commented on src/main/java/com/tripmate/controller/MemberController.java
> +                    if (memberDTO.getLogInRequestCnt() >= 5) {
로그인 실패했을 경우 memberDTO의 값이 null이라서 해당 if조건에서 NPE 발생할 것 같습니다.
의도한게 아니라면 별도 처리 필요해 보여요.

2023-01-25 05:33 UTC, freesens commented on src/main/webapp/resources/js/members/signIn.js
> +                    if (result.logInRequestCnt >= 5) {
* "0000", "5" 등은Const에 선언된 값을 js레벨에서 사용 가능하도록 상수화 해두고 쓰는게 좋으거 같습니다.
* @yuncorn 요원에게 가이드 요청 해주세요.

2023-01-25 05:33 UTC, freesens commented on src/main/java/com/tripmate/controller/MemberController.java
> +                    if (memberDTO.getLogInRequestCnt() >= 5) {
최대 로그인 실패 횟수는 상수로.

2023-01-25 05:33 UTC, freesens commented on src/main/java/com/tripmate/controller/MemberController.java
> +                    result = ApiResult.builder().code(ApiResultEnum.UNKNOWN.getCode()).message(ApiResultEnum.UNKNOWN.getMessage()).build();
```
response.getCode();
response.getMessage();
```
위의 값을 이용하여 api서버에서 전달받은 결과를 기준으로 서버 오류인지 다른 오류인지 판단해서 브라우저로 넘겨야 하지 않을까 습니다.

2023-01-25 05:33 UTC, freesens commented on src/main/java/com/tripmate/controller/MemberController.java
> +            log.error(e.getMessage(), e);
* 의도적으로 발생시키는 IOException과 그 외 예측하지 못한 exception에 대해 로그를 남기거나, 예외처리를 다르게 하는 목적으로 catch블럭을 구분해서 사용해주세요.

2023-01-25 05:33 UTC, freesens commented on src/main/java/com/tripmate/controller/MemberController.java
> +    public String signIn(HttpServletRequest request, SignInDTO signInDTO) {
* browser / front server / api server 3개의 영역에서 모두 해당 요청에 필요한 dto에 대해 validation체크를 수행해야 합니다.

2023-01-26 04:27 UTC, wjdwo951219 approved these changes

2023-01-26 04:32 UTC, cyjang-pionnet commented on src/main/webapp/resources/js/members/signIn.js
> +                        //TODO: 메인으로 이동하도록 수정
회원상세코드도 상수로 사용하면 코드값이 뭔지 잘 알 수 있을 것 같아요

2023-01-26 05:18 UTC, Ryumina approved these changes

2023-01-26 05:21 UTC, Lets-KT approved these changes

2023-01-26 05:37 UTC, freesens commented on src/main/java/com/tripmate/entity/Const.java
> +    String RESULT_CODE_UNKNOWN = "9999";
* api 서버와 동일하게 결과코드를 모두 상수로 선언할 필요가 있을지 고민 해주세요.
* success / unknown 을 제외한 나머지 오류 코드는 api서버에서 의도적으로 발생시킨 코드이기 때문에 굳이 상수화 하지 않고, api 서버에서 받은 code / message를 그대로 사용해도 무방할 것으로 보입니다.
* 실제 로직상 성공여부 판단을 위해 0000은 상수로 필요하고, 0000이 아닐때 api서버의 응답코드 9999는 예상하지 못한 오류이고, 나머지 코드는 의도한 오류이니 front쪽에서 굳이 해당 상수들을 선언할 필요성이 없을거 같습니다.

2023-01-26 05:37 UTC, freesens commented on src/main/webapp/resources/css/members/signIn.css
> +
css 및 이미지 파일들은 어차피 bypass 항목인데, 파일수가 늘어나면 리뷰시 보기 번거로우니 그냥 분리해서 따로 p/r 생성 하는게 좋을거 같습니다.

2023-01-26 05:37 UTC, freesens commented on src/main/webapp/WEB-INF/jsp/common/include/header.jsp
> +    constCode.global = (function () {
명칭을 굳이 따지자면 global.constCode여야 하는게 아닌지?

2023-01-26 06:07 UTC, freesens requested changes
드래곤볼 다 모았으면 머지 ㄱㄱ

2023-01-26 06:07 UTC, freesens approved these changes

2023-01-26 06:09 UTC, merged